#!/usr/bin/env ansible-playbook

- name: Provision an NFS server
  hosts: all
  become: true

  roles:
    # Install and Setup the NFS Server
    - nfs-server
    # Export the specified directories
    - nfs-exports
    # Setup firewall and allow only necessary services through
    - firewall