- name: Install Packages
  package:
    name: "{{ packages }}"
    state: present

- name: Start and Enable Services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ services }}"

- name: Add Firewall Rules
  firewalld:
    state: enabled
    zone: "{{ item.zone }}"
    service: "{{ item.service }}"
    permanent: yes
    immediate: yes
  with_items: "{{ rules }}"