# List of directories to export via NFS.
#
# The list should confine to the following structure:
# nfs_exports:
#   - directory: (The directory to export)
#     clients: (List of clients for the export)
#       - address: (The address of the client)
#         options: (Valid options specified at https://linux.die.net/man/5/exports)
#           - ...
#       - ...
#   - ...
#
# NOTE: This assumes the directories already exist and have been given the correct permissions.

nfs_exports:
  - directory: /opt/nfsshare
    clients:
      - address: 192.168.1.0/24
        options:
          - rw
          - sync
          - all_squash