- name: Install Packages
  package:
    name: "{{ packages }}"
    state: present

- name: Start and Enable Services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ services }}"